// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAcademicoMonolitico.src.Data;

#nullable disable

namespace SistemaAcademicoMonolitico.Migrations
{
    [DbContext(typeof(SistemaAcademicoDbContext))]
    partial class SistemaAcademicoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DisciplinaFormacao", b =>
                {
                    b.Property<int>("DisciplinasId")
                        .HasColumnType("int");

                    b.Property<int>("FormacoesId")
                        .HasColumnType("int");

                    b.HasKey("DisciplinasId", "FormacoesId");

                    b.HasIndex("FormacoesId");

                    b.ToTable("DisciplinasFormacoes", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.AlunoCursoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("Date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("Date");

                    b.Property<decimal>("Nota")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<int>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "DisciplinaId", "CursoId");

                    b.HasIndex("CursoId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Aluno_Curso_Discplina", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaConhecimento")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("Area_Conhecimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.CursoDisciplina", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<int>("CargaHoraria")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("Carga_Horaria");

                    b.Property<string>("Ementa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CursoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Cursos_Disciplinas", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaConhecimento")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("Area_Conhecimento");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.ToTable("Disciplinas", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.Formacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaConhecimento")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("Area_Conhecimento");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Nivel")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ValorPontuacao")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("Valor_Pontuacao");

                    b.HasKey("Id");

                    b.ToTable("Formacoes", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.GradeHoraria", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("Dia")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time")
                        .HasColumnName("Duracao");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time")
                        .HasColumnName("Hora_Fim");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("Hora_Inicio");

                    b.HasKey("CursoId", "DisciplinaId", "ProfessorId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Grade_Horaria", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.MatriculaAlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("Date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("Date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("Matricula_Aluno_Curso", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataContratacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Pontuacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("RegistroMec")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Professores", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.ProfessorFormacao", b =>
                {
                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("FormacaoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("Date");

                    b.Property<DateOnly>("Termino")
                        .HasColumnType("Date");

                    b.HasKey("ProfessorId", "FormacaoId");

                    b.HasIndex("FormacaoId");

                    b.ToTable("Professores_Formacoes", (string)null);
                });

            modelBuilder.Entity("DisciplinaFormacao", b =>
                {
                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Disciplina", null)
                        .WithMany()
                        .HasForeignKey("DisciplinasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Formacao", null)
                        .WithMany()
                        .HasForeignKey("FormacoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Disciplina", null)
                        .WithMany("Alunos")
                        .HasForeignKey("DisciplinaId");
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.AlunoCursoDisciplina", b =>
                {
                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Disciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Curso", "Curso")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany("CursosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Curso");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.CursoDisciplina", b =>
                {
                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany("Cursos")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.GradeHoraria", b =>
                {
                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Curso", "Curso")
                        .WithMany("Horarios")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany("Horarios")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Professor", "Professor")
                        .WithMany("Horarios")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Disciplina");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.MatriculaAlunoCurso", b =>
                {
                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Curso", "Curso")
                        .WithMany("Alunos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.ProfessorFormacao", b =>
                {
                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Formacao", "Formacao")
                        .WithMany("Professores")
                        .HasForeignKey("FormacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoMonolitico.src.Domain.Entities.Professor", "Professor")
                        .WithMany("Formacoes")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Formacao");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("Disciplinas");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("AlunosDisciplinas");

                    b.Navigation("Disciplinas");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.Disciplina", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Cursos");

                    b.Navigation("CursosDisciplinas");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.Formacao", b =>
                {
                    b.Navigation("Professores");
                });

            modelBuilder.Entity("SistemaAcademicoMonolitico.src.Domain.Entities.Professor", b =>
                {
                    b.Navigation("Formacoes");

                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
